### ISSUE TITLE
WYSIWYG editor

### ISSUE THREAD

**Issue by markseu** [markseu/yellowcms#24]
Hi! We made Yellow to be easy to use. Many said that Markdown is unusable for most people, [WYSIWYG](https://en.wikipedia.org/wiki/WYSIWYG) is the way to go. What do you need? What's a good way to edit content in a browser? 

Here's are some WYSIWYG editors for Markdown: [epiceditor](https://github.com/OscarGodson/EpicEditor), [grande](https://github.com/mduvall/grande.js), [hallo](https://github.com/bergie/hallo), [pen](https://github.com/sofish/pen), [zenpen](https://github.com/tholman/zenpen) and [more](http://mashable.com/2013/06/24/markdown-tools/).

**Comment by markseu** [comment]
I am afraid to say, that I don't have the time for maintenance and adding new features at the moment.

The WYSIWYG editor is something that should definitely be added. I would love to use it. It's high on my personal wish list. But it would take some time to integrate a user friendly Markdown editor, that supports images and extensions. Let's close this issue for now. If someone wants to work on it, please go ahead and send me a message. Happy to help!

**Comment by wunderfeyd** [comment]
As @markseu said it's a complex topic which we can't handle at the moment due to time limitations and current implementation limitations. 

Here a quick break down what has to be done (at least):
* choose a ready WYSIWYG editor or write it from scratch with following possibilities:
   * client side Markdown editor and interpretation on the client side
   * client side Markdown editor and interpretation on the server side (AJAX/JSON)
   * client side HTML editor with no Markdown interpretation at all (not preferred?)
* make sure the Markdown produced by the editor is the same as interpreted by the internal static Markdown parser
* add all YellowCMS Markdown features (like snippets, metadata) to the editor

So the whole feature request is going to be moved into the vague future. We would like to see this feature by ourselfs and are ready to discuss and brainstorm about it everytime again. Anyway, a contribution to the code by someone else is very welcome too.
