### ISSUE TITLE
Site not updated, clear cache manually

### ISSUE THREAD

**Issue by varakh** [markseu/yellowcms#47]
The page will not get updated automatically on certain scenarios:

- move folders in the content folder (e.g. change name from feed to 3-feed)
- add new folders to content folder
- editing a blog entry (with or without images) will not update the front page (Add a false image link, then add a correct one. The / and /blog-entry will not get updated)

I think, that the root page is some kind of broken concerning updates. Only clearing my browser cache helps. This has to be fixed like as soon as possible. :+1:

**Comment by markseu** [comment]
About the issue with emptying cache. Yes, this happens when you make structural changes on your website... such as snippets, templates and folders. When this happens I reload page or empty the browser cache. I see if I can find a solution.

About the issue with editing a blog entry, I was not able to reproduce it.

Thanks a lot for reporting, any additional information is appreciated!

**Comment by nibreh** [comment]
HI

By the way, I found this trick in stackoverflow :

header("Expires: Tue, 01 Jan 2000 00:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");

Put it in _yellow.php_ before _require_once("system/core/core.php");_

_This doesn't clear the user's browser cache. It does tell the browser to not cache the site._
http://stackoverflow.com/questions/1037249/how-to-clear-browser-cache-with-php

Don't know if it's a good trick or not, but it's useful when testing yellowCMS

**Comment by markseu** [comment]
I didn't know this was such a big problem, that people were using workarounds. :smile:

**Comment by nibreh** [comment]
Well, it's not really a problem for me, because I don't save cache browser (delete automatically when close browser). But most of people don't clear their cache even after years ;)

**Comment by markseu** [comment]
Good to know. I was not aware it was a problem.

Here's what I understand so far. Caching is a good thing, it reduced latency and traffic. It can also go wrong, sometimes the browser shows an old page from the browser cache. This happens because of two reasons: The browser doesn't request a new page or the CMS says that there is no new page. First case is usually not a big problem for small websites, you simply click reload. Second case is causing real problems. For example after changing content folders, the CMS doesn't tell the browser that the navigation has changed. Then you have to clean the browser cache. Not good. Let's see if we can improve it.

**Comment by varakh** [comment]
I do think that @nibreh's patch should be included by default as long as this issue isn't fixed correctly using caches. I know many people who don't press F5 to reload. They just stare at the page and see no changes at all. As the maintainer a website, I really want people to see all UPDATED contents without the help of clearing the cache or reloading the whole site. They might do that though, when they think the page should have some updated information, so traffic is not the main problem here. It is about comfort.

**Comment by markseu** [comment]
The latest version should fix caching problems. Let me know if it works, thanks!

**Comment by varakh** [comment]
Seems to be fixed. I am closing it.

**Comment by varakh** [comment]
By the way. This is **NOT** fixed. Seems still to be a problem, when I upload a new .txt file (e.g. new blog post). After pressing F5 it updates the site. Should be working without having to press F5.

**Comment by markseu** [comment]
Does this happen on your blog start page? I think what's happening is that the browser doesn't request a new page. The visitor sees the old page until someone decides to get the new page from the CMS. Let's try a cache busting/expiration technique. Add the following line to your blogarticles template:

    <?php $yellow->page->header("Cache-Control: max-age=60") ?>

Let me know how it works.

**Comment by varakh** [comment]
Not working.

**Comment by markseu** [comment]
Let's facetime/skype?

**Comment by varakh** [comment]
I don't have those things and currently no time. Maybe in 1h. Do you have jabber?

**Comment by markseu** [comment]
It was just a suggestion, sometimes things are faster to fix on the phone.  :smile: 

Sorry don't have Jabber. Can you try a smaller timeout value, e.g. 10 seconds?

**Comment by varakh** [comment]
Ok, I think it is working. Should this be default on blogarticles template? :>

**Comment by markseu** [comment]
Templates are updated. Should be working now.
